apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  MINIO_SECRET_KEY: "minio12345"
  MINIO_ROOT_PASSWORD: "minio12345"
  POSTGRES_PASSWORD: "postgres"
  MINIO_ROOT_USER: "root"
  PGADMIN_DEFAULT_PASSWORD: "postgres"