apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/database"
  SPRING_DATASOURCE_USERNAME: "postgres"
  MINIO_URL: "http://minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_BUCKET: "profile-photos"
  SERVER_PORT: "8080"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
