apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  POSTGRES_PASSWORD: "postgres"
  MINIO_ROOT_USER: "minioadmin"
  PGADMIN_DEFAULT_PASSWORD: "postgres"